version: '3'

services:
  antink-server:
    build: .
    container_name: antink-server
    privileged: true  
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse  
    security_opt:
      - apparmor:unconfined
    volumes:
      - ./it24_host:/it24_host:ro
      - ./antink_mount:/antink_mount:shared
      - ./antink-logs:/var/log:rw
    networks:
      - antink-network
    restart: unless-stopped

  antink-logger:
    image: ubuntu:20.04
    container_name: antink-logger
    depends_on:
      - antink-server
    volumes:
      - ./antink-logs:/var/log:ro
    command: >
      bash -c "apt-get update && apt-get install -y tail && 
              echo 'Starting log monitor...' && 
              tail -f /var/log/it24.log"
    networks:
      - antink-network
    restart: unless-stopped

networks:
  antink-network:
    driver: bridge
